function Fk_sym = Fk(in1,in2,Ts)
%Fk
%    Fk_sym = Fk(IN1,IN2,Ts)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    21-Dec-2025 08:31:15

bgy = in1(5,:);
bgz = in1(6,:);
phi = in1(1,:);
theta = in1(2,:);
wy = in2(2,:);
wz = in2(3,:);
t2 = cos(phi);
t3 = cos(theta);
t4 = sin(phi);
t5 = sin(theta);
t6 = tan(theta);
t8 = -wy;
t9 = -wz;
t7 = t6.^2;
t10 = 1.0./t3;
t12 = bgy+t8;
t13 = bgz+t9;
t11 = t10.^2;
t14 = t7+1.0;
Fk_sym = reshape([-Ts.*(t2.*t6.*t12-t4.*t6.*t13)+1.0,Ts.*(t2.*t13+t4.*t12),-Ts.*(t2.*t10.*t12-t4.*t10.*t13),0.0,0.0,0.0,-Ts.*(t2.*t13.*t14+t4.*t12.*t14),1.0,-Ts.*(t2.*t5.*t11.*t13+t4.*t5.*t11.*t12),0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,-Ts,0.0,0.0,1.0,0.0,0.0,-Ts.*t4.*t6,-Ts.*t2,-Ts.*t4.*t10,0.0,1.0,0.0,-Ts.*t2.*t6,Ts.*t4,-Ts.*t2.*t10,0.0,0.0,1.0],[6,6]);
end
