function Lk_sym = Lk(in1,in2,Ts)
%Lk
%    Lk_sym = Lk(IN1,IN2,Ts)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    21-Dec-2025 08:31:15

phi = in1(1,:);
theta = in1(2,:);
t2 = cos(phi);
t3 = cos(theta);
t4 = sin(phi);
t5 = tan(theta);
t6 = 1.0./t3;
Lk_sym = reshape([Ts,0.0,0.0,0.0,0.0,0.0,Ts.*t4.*t5,Ts.*t2,Ts.*t4.*t6,0.0,0.0,0.0,Ts.*t2.*t5,-Ts.*t4,Ts.*t2.*t6,0.0,0.0,0.0],[6,3]);
end
